# Skaffold for development with hot-reload
apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: wealthpath

build:
  local:
    push: false
  artifacts:
    - image: wealthpath-backend
      context: backend
      docker:
        dockerfile: Dockerfile
    - image: wealthpath-frontend
      context: frontend
      docker:
        dockerfile: Dockerfile

manifests:
  kustomize:
    paths:
      - k8s

deploy:
  kubectl: {}

portForward:
  - resourceType: service
    resourceName: frontend
    namespace: wealthpath
    port: 3000
    localPort: 3000
  - resourceType: service
    resourceName: backend
    namespace: wealthpath
    port: 8080
    localPort: 8080



