version: "2"

run:
  timeout: 5m
  go: '1.24'

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Report suspicious constructs
    - ineffassign   # Detect unused assignments
    - staticcheck   # Static analysis (includes gosimple)
    - unused        # Find unused code
    - misspell      # Find misspellings
    - bodyclose     # Check HTTP body is closed
    - gocritic      # Opinionated linter
    - errorlint     # Error wrapping checks

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  errorlint:
    errorf: true
    asserts: true
    comparison: true

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
